version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/overlays"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[docker] "
  - package-ecosystem: "docker"
    directory: "/argocd"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[docker] "
