apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kavita
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kavita
    spec:
      containers:
      - name: kavita
        image: lscr.io/linuxserver/kavita:latest
        env:
          - name: TZ
            value: "America/New_York" # Change to your timezone
          - name: PUID
            value: "1000" # Change to your PUID
          - name: PGID
            value: "1000" # Change to your PGID
        ports:
        - containerPort: 5000
          name: http
        volumeMounts:
        - mountPath: /config
          name: htpc-home
          subPath: kavita # Changed from readarr to kavita for dedicated config
        - mountPath: /books
          name: htpc-home
          subPath: media/books/books
        - mountPath: /audiobooks
          name: htpc-home
          subPath: media/books/audiobooks
        - mountPath: /comics
          name: htpc-home
          subPath: media/books/comics
        - mountPath: /downloads # This might not be strictly necessary for Kavita itself, but including as requested.
          name: htpc-home
          subPath: downloads
        resources:
          limits:
            memory: "1Gi" # Adjust as needed
            cpu: "500m"  # Adjust as needed
          requests:
            memory: "512Mi" # Adjust as needed
            cpu: "250m"   # Adjust as needed
      volumes:
      - name: htpc-home
        persistentVolumeClaim:
          claimName: htpc-home # Assuming a PVC named 'htpc-home' exists
      securityContext:
        runAsUser: 1000 # Should match PUID in configMap
        runAsGroup: 1000 # Should match PGID in configMap
        fsGroup: 1000 # Should match PGID in configMap
