apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  type: LoadBalancer
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
    name: webui
  - name: torrent-tcp
    protocol: TCP
    port: 51413
    targetPort: 51413
  - name: torrent-udp
    protocol: UDP
    port: 51413
    targetPort: 51413
  selector:
    run: transmission
