apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  ports:
  - port: 7878
    protocol: TCP
    targetPort: 7878
    name: webui
  selector:
    run: radarr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: radarr
  name: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      run: radarr
  template:
    metadata:
      labels:
        run: radarr
    spec:
      securityContext:
        # runAsUser: 1000
        # runAsGroup: 1000
        fsGroup: 1000
      initContainers:
      - name: chown
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config && chown -R 1000:1000 /movies"]
        volumeMounts:
        - mountPath: /config 
          name: htpc-home
          subPath: radarr    
        - mountPath: /movies 
          name: htpc-home
          subPath: media/movies      
      - name: config
        image: busybox
        command: ["sh", "-c"]
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000        
        args:
          - "echo start;[[ ! -f /config/config.xml ]] && echo '<Config><UrlBase>/$(RADARR)</UrlBase></Config>'> /config/config.xml;echo end;"
        volumeMounts: 
        - mountPath: /config 
          name: htpc-home
          subPath: radarr
      containers:
      - env:
        - name: TZ
          value: America/Sao_Paulo
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        image: linuxserver/radarr
        name: radarr
        ports:
        - containerPort: 7878
          name: webui
        livenessProbe:
          exec:
            command:
            - curl "http://localhost:7878/radarr/api/health?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          exec:
            command:
            - curl "http://localhost:7878/radarr/api/system/status?ApiKey=$(sed -ne '/ApiKey/{s/.*<ApiKey>\(.*\)<\/ApiKey>.*/\1/p;q;}' </config/config.xml)"
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts: 
        - mountPath: /config 
          name: htpc-home
          subPath: radarr
        - mountPath: /movies 
          name: htpc-home
          subPath: media/movies
        - mountPath: /downloads 
          name: htpc-home
          subPath: downloads        

